version: '3'

services:
  db:
    image: mysql:5.7
    volumes:
      - ukraine-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ukraine
      MYSQL_PASSWORD: db_password
      MYSQL_USER: db_user
    ports:
      - "15306:3306"

volumes:
  ukraine-mysql-data: